In [34]:
import numpy as np
from scipy import sparse

from IPython.display import display
from IPython.display import Latex

# 6.1 Matrices

## Creating matrices from the entries

Matrices can be represented in Python using 2-dimensional numpy array or list structure (list of lists). For example, the 3 × 4 matrix
$$A =\begin{bmatrix}
0 && 1 && −2.3 && 0.1 \\
1.3 && 4 && −0.1 && 1 \\
4.1 && −1 && 0 && 1.7
\end{bmatrix}$$
is constructed in Python as

In [2]:
A = np.array([[0.0, 1.0, -2.3, 0.1],
               [1.3, 4.0, -0.1, 0.0],
               [4.1, -1.0, 0.0, 1.7]])
print(A)

[[ 0.   1.  -2.3  0.1]
 [ 1.3  4.  -0.1  0. ]
 [ 4.1 -1.   0.   1.7]]


In [3]:
m, n = A.shape  # shape property: shape of an array
print('m:', m)
print('n:', n)
display(Latex(r'size of matrix A: $%i \times %i$' % (m, n)))

m: 3
n: 4


<IPython.core.display.Latex object>

In [4]:
isTall = lambda X: A.shape[0] > A.shape[1]
isWide = lambda X: A.shape[0] < A.shape[1]
isSquare = lambda X: A.shape[0] == A.shape[1]
print('matrix A is tall:', isTall(A))
print('matrix A is wide:',isWide(A))
print('matrix A is square:',isSquare(A))

matrix A is tall: False
matrix A is wide: True
matrix A is square: False


## Indexing entries

In [5]:
# Coordinates can be interpreted as y,x or list index, item index
print(A)
display(Latex('$A_{13}=%.1f, \quad A_{32}=%.1f$' % (A[0,2], A[2,1])))

[[ 0.   1.  -2.3  0.1]
 [ 1.3  4.  -0.1  0. ]
 [ 4.1 -1.   0.   1.7]]


<IPython.core.display.Latex object>

## Equality of matrices

In [6]:
A = np.array([[0, 1, -2.3, 0.1],
              [1.3, 4, -0.1, 0],
              [4.1, -1.0, 0, 1.7]])
B = A.copy()
A == B  # element-wise

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [7]:
np.array_equal(A, B)

True

In [8]:
B[0,3] = 100  # re-assign one of the elements in B
np.sum(A==B)

11

## Row and column vectors

n-vectors are the same as n × 1 matrices. In Python, there is a subtle difference between a 1D array, a column vector and a row vector.

In [9]:
# a 3 vector
a = np.array([-2.1, -3, 0])
a.shape

(3,)

In [10]:
# a 3-vector or a 3 by 1 matrix
b = np.array([[-2.1],
              [-3],
              [0]])
b.shape

(3, 1)

In [11]:
# a 3-row vector or a 1 by 3 matrix
c = np.array([[-2.1, -3, 0]])
c.shape

(1, 3)

You can see a has shape (3,), meaning that it is a 1D array, while b has shape (3, 1), meaning that it is a 3 × 1 matrix. This small subtlety generally won’t affect you and b can be reshaped to look like c easily with the command `b.reshape(3)`.

In [12]:
a @ a  # float

13.41

In [13]:
b.T @ b

array([[13.41]])

In [14]:
c @ c.T

array([[13.41]])

## Slicing and submatrices

In [15]:
A = np.array([[-1, 0, 1, 0],
              [2, -3, 0, 1],
              [0, 4, -2, 1]])
A[0:2, 2:4]  # A_{1:2,3:4}

array([[1, 0],
       [0, 1]])

In [16]:
# Third column of A
A[:, 2]

array([ 1,  0, -2])

In [17]:
# Second row of A, returned as vector
A[1, :]

array([ 2, -3,  0,  1])

In [18]:
A.reshape((6, 2))

array([[-1,  0],
       [ 1,  0],
       [ 2, -3],
       [ 0,  1],
       [ 0,  4],
       [-2,  1]])

In [19]:
A.reshape((3, 2))

ValueError: cannot reshape array of size 12 into shape (3,2)

## Block matrices

In [20]:
B = np.array([0, 2, 3])  # 1 by 3 matrix
C = np.array([-1])  # 1 by 1 matrix
D = np.array([[2, 2, 1],
              [1, 3, 5]])  # 2 by 3 matrix
E = np.array([[4],
              [4]])  # 2 by 1 matrix
# Constrcut 3 by 4 block matrix
A = np.block([[B, C],
              [D, E]])
A

array([[ 0,  2,  3, -1],
       [ 2,  2,  1,  4],
       [ 1,  3,  5,  4]])

## Column and row interpretation of a matrix

An m × n matrix A can be interpreted as a collection of n m-vectors (its columns) or a collection of m n-row-vectors (its rows). Column vectors can be converted into a matrix using the horizontal function `np.hstack()` and row vectors can be converted into a matrix using the vertical function `np.vstack()`.

In [21]:
a = [1, 2]
b = [4, 5]
c = [7, 8]
A = np.vstack([a, b, c])
B = np.hstack([a, b, c])
print('matrix A :', A)
print('dimensions of A :', A.shape)
print('matrix B :', B)
print('dimensions of B :', B.shape)

matrix A : [[1 2]
 [4 5]
 [7 8]]
dimensions of A : (3, 2)
matrix B : [1 2 4 5 7 8]
dimensions of B : (6,)


In [22]:
a = [[1],
     [2]]
b = [[4],
     [5]]
c = [[7],
     [8]]
A = np.vstack([a, b, c])
B = np.hstack([a, b, c])
print('matrix A :', A)
print('dimensions of A :', A.shape)
print('matrix B :', B)
print('dimensions of B :', B.shape)


matrix A : [[1]
 [2]
 [4]
 [5]
 [7]
 [8]]
dimensions of A : (6, 1)
matrix B : [[1 4 7]
 [2 5 8]]
dimensions of B : (2, 3)


Another useful expression is `np.c_` and `np.r_`, which allow us to stack column (and row) vectors with other vectors (and matrices).

In [23]:
np.c_[-np.identity(3), np.zeros(3)]

array([[-1., -0., -0.,  0.],
       [-0., -1., -0.,  0.],
       [-0., -0., -1.,  0.]])

In [24]:
np.r_[np.identity(3), np.zeros((1, 3))]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

# 6.2 Zero and identity matrices

## Zero matrices

A zero matrix of size m × n is created using np.zeros((m,n)). Note the double brackets!

In [25]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

## Identity matrices

In [26]:
np.identity(4)  # Return the identity array. The identity array is a square array with ones on the main diagonal.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.eye(3)  # Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [29]:
np.eye(3, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Ones matrix

In VMLS we do not use special notation for a matrix with all entries equal to one. In Python, such a matrix is given by `np.ones((m,n))`

## Diagonal matrices

In standard mathematical notation, ***diag***(1, 2, 3) is a diagonal 3×3 matrix with diagonal entries 1, 2, 3. In Python, such a matrix can be created using `np.diag()`.

In [30]:
x = np.array([[0, 1, 2],
              [3, 4, 5]])
print(np.diag(x))  # extracts the diagonal entries as a vector (array)
print(np.diag(x, k=1))  # extracts the diagonal entries as a vector (array)

[0 4]
[1 5]


In [31]:
print(np.diag(np.diag(x)))  # constructs a diagonal matrix with diagonal entries given in the 1-D array.

[[0 0]
 [0 4]]


## Random matrices

In [32]:
rng = np.random.default_rng(6492)
rng.random((2, 3))

array([[0.30896411, 0.62359332, 0.8621308 ],
       [0.32927195, 0.78657859, 0.89597358]])

In [33]:
rng.standard_normal((2, 3))

array([[ 0.78963386, -0.24620154, -0.35860942],
       [ 1.04575694,  0.909243  ,  0.57325084]])

## Sparse matrices

In [36]:
I = np.array([ 0, 1, 1, 0, 2, 3 ]) # row indexes of nonzeros
J = np.array([ 0, 0, 1, 2, 2, 3 ]) # column indexes
V = np.array([ -1.11, 0.15, -0.10, 1.17, -0.30, 0.13 ]) # values
A = sparse.coo_matrix((V, (I, J)), shape=(4, 5))
A

<4x5 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in COOrdinate format>

In [37]:
A.nnz  # Number of stored values, including explicit zeros.

6

In [38]:
A.todense()  # Return a dense matrix representation of this matrix.

matrix([[-1.11,  0.  ,  1.17,  0.  ,  0.  ],
        [ 0.15, -0.1 ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  , -0.3 ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.13,  0.  ]])

In [42]:
A.toarray()  # Return a dense ndarray representation of this matrix.

array([[-1.11,  0.  ,  1.17,  0.  ,  0.  ],
       [ 0.15, -0.1 ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  , -0.3 ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.13,  0.  ]])

In [45]:
diagonals = [[1, 2, 3, 4], [1, 2, 3], [1, 2]]
B = sparse.diags(diagonals, offsets=[0, -1, 2])  # Construct a sparse matrix from diagonals.
B.toarray()

array([[1., 0., 1., 0.],
       [1., 2., 0., 2.],
       [0., 2., 3., 0.],
       [0., 0., 3., 4.]])

A useful function for creating a random sparse matrix is sparse.rand(). It generates a sparse matrix of a given shape and density with uniformly distributed values.

In [46]:
matrix = sparse.rand(3, 4, density=0.25, format='csr', random_state=42)
matrix

<3x4 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

# 6.3 Transpose, addition, and norm

In VMLS we denote the transpose of an m×n matrix A as $A^T$. In Python, the transpose of A is given by np.transpose(A) or simply A.T.

In [47]:
H = np.array([[0, 1, -2, 1],
              [2, -1, 3, 0]])
H.T

array([[ 0,  2],
       [ 1, -1],
       [-2,  3],
       [ 1,  0]])

In [48]:
np.transpose(H)

array([[ 0,  2],
       [ 1, -1],
       [-2,  3],
       [ 1,  0]])

## Addition, subtraction, and scalar multiplication

In [49]:
U = np.array([[0, 4],
              [7, 0],
              [3, 1]])
V = np.array([[1, 2],
              [2, 3],
              [0, 4]])
U + V

array([[1, 6],
       [9, 3],
       [3, 5]])

In [50]:
2.2 * U

array([[ 0. ,  8.8],
       [15.4,  0. ],
       [ 6.6,  2.2]])

## Elementwise operations

In [52]:
U + V * 0.5 

array([[0.5, 5. ],
       [8. , 1.5],
       [3. , 3. ]])

## Matrix norm

In VMLS we use $\left\|A\right\|$ to denote the norm of an m × n matrix, 
$$
\left\|A\right\| = \Bigg( \sum_{i=1}^{m}\sum_{j=1}^{n} A_{ij}^2 \Bigg)^{{1}/{2}}
$$
In standard mathematical notation, this is more often written as $\left\|A\right\|_F$ , where F stands for the name Frobenius. **In standard mathematical notation, $\left\|A\right\|$ usually refers to another norm of a matrix, which is beyond the scope of topics in VMLS.** In Python, `np.linalg.norm(A)` gives the (Forbenius) norm used in VMLS.

https://en.wikipedia.org/wiki/Matrix_norm

In [53]:
"""
The following norms can be calculated:

=====  ============================  ==========================
ord    norm for matrices             norm for vectors
=====  ============================  ==========================
None   Frobenius norm                2-norm
'fro'  Frobenius norm                --
'nuc'  nuclear norm                  --
inf    max(sum(abs(x), axis=1))      max(abs(x))
-inf   min(sum(abs(x), axis=1))      min(abs(x))
0      --                            sum(x != 0)
1      max(sum(abs(x), axis=0))      as below
-1     min(sum(abs(x), axis=0))      as below
2      2-norm (largest sing. value)  as below
-2     smallest singular value       as below
other  --                            sum(abs(x)**ord)**(1./ord)
=====  ============================  ==========================
"""
A = np.array([[2, 3, -1],
              [0, -1, 4]])
np.linalg.norm(A)

5.5677643628300215

In [54]:
np.linalg.norm(A[:])

5.5677643628300215

## Triangle inequality

$ \left\| A + B \right\| \le \left\| A \right\| + \left\| B \right\| $

In [55]:
A = np.array([[-1, 0],
              [2, 2]])
B = np.array([[3, 1],
              [-3, 2]])
print(np.linalg.norm(A + B))  # Frobenius norm
print(np.linalg.norm(A) + np.linalg.norm(B))

4.69041575982343
7.795831523312719


# 6.4 Matrix-vector multiplication

In Python, matrix-vector multiplication has the natural syntax `y = A @ x`. Alternatively, we can use the numpy function `np.matmul(A, x)`.

In [56]:
A = np.array([[0, 2, -1],
              [-2, 1, 1]])
x = np.array([2, 1, -1])
A @ x

array([ 3, -4])

In [57]:
np.matmul(A, x)

array([ 3, -4])

## Difference matrix

- (n − 1) × n difference matrix is
$$
D = \begin{bmatrix}
-1 && 1 && 0 && \cdots && 0 && 0 && 0 \\
0 && -1 && 1 && \cdots && 0 && 0 && 0 \\
 &&  && \ddots && \ddots &&  &&  &&  \\
 &&  && && \ddots && \ddots &&  &&  \\
0 && 0 && 0 && \cdots && -1 && 1 && 0 \\
0 && 0 && 0 && \cdots && 0 && -1 && 1
\end{bmatrix}
$$
y = Dx is (n − 1)-vector of differences of consecutive entries of x:
$$
Dx = \begin{bmatrix}
x_2 - x_1 \\
x_3 - x_2 \\
\vdots \\
x_n - x_{n-1}
\end{bmatrix}
$$

- Dirichlet energy: $\left\|Dx\right\|^2$ is measure of wiggliness for x a time series

https://en.wikipedia.org/wiki/Dirichlet_energy

In [64]:
diff_mat = lambda n: np.c_[-np.identity(n - 1), np.zeros(n - 1)] + np.c_[np.zeros(n - 1), np.identity(n - 1)]
D = diff_mat(4)
x = np.array([-1, 0, 2, 1])
print('D =', D)
D @ x

D = [[-1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0. -1.  1.]]


array([ 1.,  2., -1.])

Since a difference matrix contains many zeros, this is a good opportunity to use sparse matrices. Here we use the `sparse.hstack()` function to stack the sparse matrices.

In [66]:
diff_mat = lambda n: sparse.hstack([-sparse.eye(n - 1), sparse.coo_matrix((n - 1, 1))]) \
                     + sparse.hstack([sparse.coo_matrix((n - 1, 1)), sparse.eye(n - 1)])
D = diff_mat(4)
D @ np.array([-1, 0, 2, 1])

array([ 1.,  2., -1.])

## Running sum matrix

The n × n matrix
$$
S = \begin{bmatrix}
1 && 0 && 0 && \cdots && 0 && 0 && 0 \\
1 && 1 && 0 && \cdots && 0 && 0 && 0 \\
 &&  && \ddots && \ddots &&  &&  &&  \\
 &&  && && \ddots && \ddots &&  &&  \\
1 && 1 && 1 && \cdots && 1 && 1 && 0 \\
1 && 1 && 1 && \cdots && 1 && 1 && 1
\end{bmatrix}
$$
is called the running sum matrix. The ith entry of the n-vector Sx is the sum of the first i entries of x:
$$
Sx = \begin{bmatrix}
x_1 \\
x_1 + x_2 \\
x_1 + x_2 + x_3 \\
\vdots \\
x_1 + x_2 + \cdots + x_n \\
\end{bmatrix}
$$

In [67]:
def running_sum(n):
    S = np.zeros((n, n))
    for i in range(n):
        for j in range(i+1):
            S[i, j] = 1
    return S
running_sum(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [70]:
def running_sum(n):
    S = np.tril(np.ones((n, n)))
    return S
running_sum(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [72]:
running_sum(4) @ np.array([-1, 1, 2, 0])

array([-1.,  0.,  2.,  2.])

# Vandermonde matrix

Suppose the entries of the n-vector c are the coefficients of a polynomial p of degree n − 1 or less:
$$ p(t) = c_1 + c_2 t + · · · + c_{n−1} t^{n−2} + c_n t^{n−1} $$
Let $t_1, \ldots , t_m$ be m numbers, and define the m-vector y as $y_i = p(t_i)$. Then we have y = Ac, where A is the m × n matrix
$$
A = \begin{bmatrix}
1 && t_1 && \cdots && t_1^{n-2} && t_1^{n-1} \\
1 && t_2 && \cdots && t_2^{n-2} && t_2^{n-1} \\
\vdots && \vdots &&  && \vdots && \vdots \\
1 && t_{m-1} && \cdots && t_{m-1}^{n-2} && t_{m-1}^{n-1} \\
1 && t_m && \cdots && t_{m}^{n-2} && t_{m}^{n-1}
\end{bmatrix}
$$
So multiplying a vector c by the matrix A is the same as evaluating a polynomial with coefficients c at m points.

In [73]:
def vandermonde(t, n):
    m = len(t)
    V = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            V[i, j] = t[i]**(j)
    return V
vandermonde(np.array([-1, 0, 0.5, 1]), 5)

array([[ 1.    , -1.    ,  1.    , -1.    ,  1.    ],
       [ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 1.    ,  0.5   ,  0.25  ,  0.125 ,  0.0625],
       [ 1.    ,  1.    ,  1.    ,  1.    ,  1.    ]])

In [74]:
# np.column_stack(tup): Stack 1-D arrays as columns into a 2-D array.
vandermonde = lambda t,n: np.column_stack([t**i for i in range(n)])
vandermonde(np.array([-1, 0, 0.5, 1]), 5)

array([[ 1.    , -1.    ,  1.    , -1.    ,  1.    ],
       [ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 1.    ,  0.5   ,  0.25  ,  0.125 ,  0.0625],
       [ 1.    ,  1.    ,  1.    ,  1.    ,  1.    ]])

# 6.5 Complexity

Complexity of matrix-vector multiplication. The complexity of multiplying an m × n matrix by an n-vector is **m(2n − 1) ≈ 2mn** flops. (for sparse A, around 2nnz(A) flops)

This grows linearly with both m and n. Let’s check this

In [76]:
A = np.random.random((1000, 10000))
x = np.random.random(10000)
%timeit y = A @ x  # 1x

2.95 ms ± 175 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [77]:
A = np.random.random((5000, 10000))
x = np.random.random(10000)
%timeit y = A @ x  # ~5x

15.9 ms ± 399 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [78]:
A = np.random.random((1000, 20000))
x = np.random.random(20000)
%timeit y = A @ x  # ~2x

6.69 ms ± 180 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


The increase in efficiency obtained by sparse matrix computations is seen from matrix-vector multiplications with the difference matrix.

In [79]:
n = 10**4;
Ds = sparse.hstack([-sparse.eye(n-1), sparse.coo_matrix((n-1, 1))]) \
     + sparse.hstack([sparse.coo_matrix((n-1, 1)), sparse.eye(n-1)])
D = np.column_stack([np.eye(n-1), np.zeros(n-1)]) + np.column_stack([np.zeros(n-1), np.eye(n-1)])
x = np.random.normal(size=n)
%timeit D @ x
%timeit Ds @ x

30.2 ms ± 693 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
26.5 µs ± 708 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
